apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: msa-lec-ticketing
  artifacts:
    - image: us.gcr.io/msa-lec-ticketing/auth
      context: ../auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
